### ISSUE TITLE
Reconsider operator confirmation for TACO app

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#103]
Operator confirmation for SimplePREApp made sense as a soft measure to ensure that operators had a correct node set up. This was particularly necessary for PRE since it was difficult to collect on-chain evidence of nodes not following the protocol.

For Taco, however, we have on-chain trails on the Coordinator contract (on Polygon), and this information will be used as input to the Merkle tree-based rewards distribution mechanism (and in the future, for slashing purposes). IMO, an additional node confirmation on Ethereum is just an operational overhead for stakers, and doesn't provide further assurance over withholding rewards to nodes for which we can check on the Coordinator contract that they haven't followed the protocol (e.g., by not posting transcripts or aggregates on ritual initialization)

**Comment by cygnusv** [comment]
Previous discussion: https://github.com/nucypher/nucypher-contracts/pull/99#discussion_r1266519690

**Comment by vzotova** [comment]
Ideally I'd do that onchain only, to have a proof of owning operator address (obtain data from Coordinator). 
Else if we would like to have optimistic approach - then we want a way to connect merkle tree and slashing in app. Otherwise trolling will be very easy (because we still will have timeout for bonding)

**Comment by cygnusv** [comment]
What do you mean by trolling in this case? We can have a time delay for bonding to a new operator, so if a staker wants to troll, they risk not making it for new DKG requests.

**Comment by derekpierre** [comment]
> for which we can check on the Coordinator contract that they haven't followed the protocol (e.g., by not posting transcripts or aggregates on ritual initialization)

Does this assume that the node is eventually sampled to be part of a cohort...there could be an unknown (long or short) time difference between when the node is supposedly set up and when they are eventually sampled. Is it ok to consider the node as optimistically properly set up during that interim timeframe?

Because the DKG ritual only needs one non-responsive/not properly setup node to fail, perhaps it could be a good thing to deal with incorrectly set up nodes earlier (as part of operator confirmation) than at ritual time...?

**Comment by derekpierre** [comment]
> I don't see a problem with that. Besides, we already have an existing set-up TX that's meaningful from a protocol perspective, which is the call to Coordinator.setProviderPublicKey().

Right. Forgot about that. I guess we are basically replacing `confirmOperator()` (mainnet) with `setProviderPublicKey()` (polygon). Presumably the call to `setProviderPublicKey` will happen on first startup.

**Comment by derekpierre** [comment]
@cygnusv this is done, correct?

Only `Coordinator.setProviderPublicKey()` is now performed on Polygon, which then calls `TACoChildApplication.confirmOperatorAddress` which then goes through the Polygon->Eth bridge to then eventually call `TACoApplication.confirmOperatorAddress` on Ethereum (root).

**Comment by derekpierre** [comment]
I believe this is done.

@cygnusv if not, please reopen.

**Comment by cygnusv** [comment]
It's almost done. The remaining part is tracked by https://github.com/nucypher/nucypher/issues/3251, so we can leave this one closed.
