### ISSUE TITLE
Rework `ProxyAdmin` deployment handling for OZ v5+

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher-contracts#164]

**Comment by cygnusv** [comment]
In OZv5, `TransparentUpgradeableProxy` deploys its own new `ProxyAdmin` contract at construction time (see https://github.com/OpenZeppelin/openzeppelin-contracts/blob/932fddf69a699a9a80fd2396fd1a2ab91cdda123/contracts/proxy/transparent/TransparentUpgradeableProxy.sol#L78). One the one hand this makes the deployment configuration a bit easier because we don't have to deploy it, but on the other hand, difficulties subsequent steps that require to know the `ProxyAdmin`'s address.

Three ways to get this, from the proxy's deployment TX:
1. Obtain a list of contracts deployed during the TX; one of the is the `TransparentUpgradeableProxy`, the other is its `ProxyAdmin`. I don't know how to do this, but should be doable, I guess?
2. Look for an `AdminChanged` event, emitted by the proxy. The new `admin` of the proxy is `ProxyAdmin` (see https://github.com/OpenZeppelin/openzeppelin-contracts/blob/932fddf69a699a9a80fd2396fd1a2ab91cdda123/contracts/proxy/ERC1967/ERC1967Utils.sol#L128)
3. Look for a `OwnershipTransferred` event, emitted by the `ProxyAdmin` (see https://github.com/OpenZeppelin/openzeppelin-contracts/blob/932fddf69a699a9a80fd2396fd1a2ab91cdda123/contracts/access/Ownable.sol#L98)

Maybe by doing 2 and 3 and cross-checking is more than enough.

**Comment by KPrasch** [comment]
`ProxyAdmin` deployments and artifacts tracking were removed in https://github.com/nucypher/nucypher-contracts/pull/160/commits/b4b1695deea7d2d2c67d51cd8f3eb641c368594e

**Comment by cygnusv** [comment]
Additional option (and probably the simplest and preferred one):
4. `TransparentUpgradeableProxy` complies with `ERC1967`, which defines an `admin` slot at storage location `0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103`. To read it, we need to directly access a storage slot, so we have to use the JSON-RPC method `eth_getStorageAt` with parameters `(proxy address, admin slot address, block number)`; being more specific: `(proxy address, 0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103, 'latest')`.
See https://github.com/OpenZeppelin/openzeppelin-contracts/blob/94697be8a3f0dfcd95dfb13ffbd39b5973f5c65d/contracts/proxy/ERC1967/ERC1967Utils.sol#L104

**Comment by derekpierre** [comment]
2) is made easier by the fact that we store the transaction hash for the deployment of the `TransparentUpgradeableProxy` contract in the contract registry - so we can look at the logs for the tx and get the `AdminChanged` event.

**Comment by derekpierre** [comment]
Can this be closed?

**Comment by cygnusv** [comment]
Yes. For reference, we support option 4 outlined here (https://github.com/nucypher/nucypher-contracts/issues/164#issuecomment-1788638680) but since upgradeable contracts require an admin role to actually execute the upgrade, `ProxyAdmin` is not relevant for the moment.
